name: say_hello

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '59 12,23 * * *' #utc换算北京时间，19:59 07:59
    
jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.9' ]

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Working
        run: |
          python main.py
        env:
          JD_Cookie: ${{ secrets.JD_Cookie }}
