name: say_hello

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - 'master'
  workflow_dispatch: # 手动触发

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.9' ]

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target=/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages -r requirements.txt
          pip list

      - name: Say Hello
        run: |
          python main.py
